In [1]:
import os
import os
import psycopg2
from psycopg2 import extras
import pandas as pd
from dotenv import load_dotenv
import numpy as np

In [2]:
load_dotenv()
db_conn_string = os.getenv("DATABASE_CONN_STRING")

In [3]:
conn = psycopg2.connect(db_conn_string)

In [6]:
pd.read_sql("SELECT * FROM blackjack_odds where dealer_hit_soft_17 = True and double_after_split = True and blackjack_pays = 1.5", conn)

C:\Users\amarl\AppData\Local\Temp\ipykernel_13912\2946765883.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("SELECT * FROM blackjack_odds where dealer_hit_soft_17 = True and double_after_split = True and blackjack_pays = 1.5", conn)

,id,player_total,dealer_card_up,double_ev,hit_ev,stand_ev,split_ev,best_action,dealer_hit_soft_17,double_after_split,blackjack_pays,surrender_allowed
0,1321,20,2,-1.707052,-0.853526,0.634011,NaN,stand,True,True,1.5,True
1,1322,20,3,-1.708452,-0.854226,0.644469,NaN,stand,True,True,1.5,True
2,1323,20,4,-1.708827,-0.854414,0.655167,NaN,stand,True,True,1.5,True
3,1324,20,5,-1.706887,-0.853444,0.668759,NaN,stand,True,True,1.5,True
4,1325,20,6,-1.706162,-0.853081,0.675032,NaN,stand,True,True,1.5,True
...,...,...,...,...,...,...,...,...,...,...,...,...
325,1646,paired_aces,7,0.270898,0.198859,-0.473735,1.542132,split,True,True,1.5,True
326,1647,paired_aces,8,0.199617,0.126101,-0.509630,1.417120,split,True,True,1.5,True
327,1648,paired_aces,9,0.116514,0.042663,-0.543080,1.262381,split,True,True,1.5,True
328,1649,paired_aces,10,0.044383,-0.025115,-0.497135,1.035177,split,True,True,1.5,True
329,1650,paired_aces,11,0.030255,-0.019078,-0.410514,0.795772,split,True,True,1.5,True